services:
  web:
    build: .
    ports:
      - "8080:8080"
    container_name: springboot-thymeleaf-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
  
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: contactenos
      MYSQL_USER: grupo_web
      MYSQL_PASSWORD: grupo_web
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    restart: unless-stopped

  sonarqube_db:
    image: postgres:latest
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mysql_data:
  sonarqube_db_data:
